In [1]:
import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.sentiment import SentimentIntensityAnalyzer
from collections import Counter
from wordcloud import WordCloud

In [2]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('vader_lexicon')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package vader_lexicon to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [3]:
pd.read_csv("spam.csv")

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [16]:
stop_words=set(stopwords.words('english'))

def clean_text(text):
  text=text.lower()
  text=re.sub('[^a-zA-Z]'," ",text)
  words=word_tokenize(text)
  words=[word for word in words if word not in stop_words]
  cleaned_text=" ".join(words)
  return cleaned_text

df["Cleaned_email"] = df["text"].apply(clean_text)
display(df[['text','Cleaned_email']])

,text,Cleaned_email
0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,"Nah I don't think he goes to usf, he lives aro...",nah think goes usf lives around though
...,...,...
5567,This is the 2nd time we have tried 2 contact u...,nd time tried contact u u pound prize claim ea...
5568,Will Ã¼ b going to esplanade fr home?,b going esplanade fr home
5569,"Pity, * was in mood for that. So...any other s...",pity mood suggestions
5570,The guy did some bitching but I acted like i'd...,guy bitching acted like interested buying some...
5571,Rofl. Its true to its name,rofl true name

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [19]:
X_train, X_test, y_train, y_test = train_test_split(df['cleaned_text'], df['label_encoded'], test_size=0.2, random_state=42)

print(f"Training samples: {len(X_train)}")
print(f"Testing samples: {len(X_test)}")

Training samples: 4457
Testing samples: 1115

In [20]:

vectorizer = CountVectorizer()
X_train_vectorized = vectorizer.fit_transform(X_train)
X_test_vectorized = vectorizer.transform(X_test)

print(f"Vocabulary size: {len(vectorizer.vocabulary_)}")

Vocabulary size: 7451

In [21]:
model = MultinomialNB()
model.fit(X_train_vectorized, y_train)

print("Model trained successfully!")

Model trained successfully!

In [22]:

y_pred = model.predict(X_test_vectorized)


accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-Score: {f1:.4f}")
print("Confusion Matrix:\n", conf_matrix)

Accuracy: 0.9830
Precision: 0.9577
Recall: 0.9128
F1-Score: 0.9347
Confusion Matrix:
 [[960   6]
 [ 13 136]]